spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/grandma_db
    password: password

  sql:
    init:
      mode: always
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
