spring:
  profiles:
    active: dev

  application:
    name: training-new-gen

  jackson:
    time-zone: America/Bogota
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

springdoc:
  api-docs:
    path: /v1/api-docs

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

