services:
  database_service  :
    image: bitnami/postgresql:latest
    container_name: grandma_db
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=grandma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql


volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge